# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/.Xil/Vivado-11804-LAPTOP-QTLDDFS4/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a35ticsg324-1L
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class0_adder.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class0_tree0.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class0_tree1.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class0_tree2.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class0_tree3.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class0_tree4.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class0_tree5.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class0_tree6.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class1_adder.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class1_tree0.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class1_tree1.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class1_tree2.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class1_tree3.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class1_tree4.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class1_tree5.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class1_tree6.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class2_adder.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class2_tree0.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class2_tree1.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class2_tree2.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class2_tree3.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class2_tree4.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class2_tree5.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class2_tree6.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class3_adder.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class3_tree0.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class3_tree1.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class3_tree2.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class3_tree3.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class3_tree4.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class3_tree5.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class3_tree6.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class4_adder.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class4_tree0.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class4_tree1.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class4_tree2.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class4_tree3.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class4_tree4.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class4_tree5.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class4_tree6.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class5_adder.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class5_tree0.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class5_tree1.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class5_tree2.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class5_tree3.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class5_tree4.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class5_tree5.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class5_tree6.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class6_adder.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class6_tree0.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class6_tree1.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class6_tree2.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class6_tree3.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class6_tree4.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class6_tree5.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/class6_tree6.v}
      {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/verilog/TreeLUT.v}
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top TreeLUT
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/.Xil/Vivado-11804-LAPTOP-QTLDDFS4/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/willi/OneDrive/햞ea de Trabalho/ScriptSinteseVivado/.Xil/Vivado-11804-LAPTOP-QTLDDFS4/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
   return -code "error" $rt::result
 }
}
